const Product = [
    {
        id: 1,
        name: 'The Witcher 3: Wild Hunt',
        genre: 'RPG',   
        date: '19 мая 2015г',
        platform: 'PC Play Station 4',
        rating: 8.0,
        image: 'https://cdn.kanobu.ru/games/66/ca88bfd116154e0ba95708149306be50',
        description: 'The Witcher 3: Wild Hunt -  компьютерная ролевая игра по мотивам серии романов «Ведьмак» польского писателя Анджея Сапковского, продолжение игр «Ведьмак» и «Ведьмак 2: Убийцы королей».',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'The Witcher 3: Wild Hunt -  компьютерная ролевая игра по мотивам серии романов «Ведьмак» польского писателя Анджея Сапковского, продолжение игр «Ведьмак» и «Ведьмак 2: Убийцы королей». Заключительная часть трилогии. Игроку вновь отводится роль Геральта, ведьмака, убивающего монстров. После событий второй части Геральт возвращает утраченные воспоминания, и оказывается на перепутье. В Северных королевствах бушует война, а неожиданно вернувшаяся Йеннифэр, подруга Геральта, просит его помочь с поисками Цириллы, Дитя-неожиданности, которая может остановить пришествие Дикой Охоты. Геральт отправляется в опасное путешествие по разоренным войной землям, чтобы найти Цири и сокрушить Дикую Охоту раз и навсегда.',
        OC: '64-bit Windows 7, 64-bit Windows 8 (8.1)',       
        Proc: 'Intel CPU Core i5-2500K 3.3GHz / AMD CPU Phenom II X4 940',
        Vcard: 'Nvidia GPU GeForce GTX 660 / AMD GPU Radeon HD 7870',
        OCR: 6.0,
        RCD: 35.0,
        RecOC: '64-bit Windows 8 (8.1) or 64-bit Windows 10',       
        RecProc: 'Intel CPU Core i7 3770 3.4 GHz / AMD CPU AMD FX-8350 4 GHz',
        RecVcard: 'Nvidia GPU GeForce GTX 770 / AMD GPU Radeon R9 290',
        RecOCR: 8.0,
        RecRCD: 35.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/91/412455f5-a5a4-4985-9c04-97c5390491d3.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/91/cd64e8d0-da56-41f5-956e-fd0ba7d48f3c.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/2304ce89-aa9f-49d9-8eb7-ab8f5d15a0dd.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/3ae28aa0-4f0d-499d-a150-342033f4cd0a.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/62b9f403-2be7-4b42-8f9f-91cc29e1cd0d.webp',
    },
    {
        id: 2,
        name: 'Metal Gear Solid 5: The Phantom Pain',
        genre: 'Экшен, Шутеры',   
        date: '1 сентября 2015г',
        platform: 'PlayStation 4, Xbox One,',
        rating: 7.9,
        image: 'https://cdn.kanobu.ru/games/2bfa235a-25dc-488c-be62-dde9fa7d72fe.webp',
        description: 'Metal Gear Solid 5 - это компьютерная игра жанра стелс-экшн. Она будет десятой сюжетной игрой в серии Metal Gear и первой, в которой будет присутствовать открытый мир. Игра предлагает тактическую большое разнообразие',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Metal Gear Solid V: The Phantom Pain — это тактический шпионский экшен от Хидео Кодзимы, завершающий сагу о Биг Боссе. События игры разворачиваются в 1984 году, спустя девять лет после происшествий Ground Zeroes. Главный герой, Веном Снейк (Big Boss), пробуждается от комы и отправляется мстить за уничтожение своей базы. Игроку предстоит возглавить организацию «Diamond Dogs», построить новую базу (Mother Base) и проводить миссии по всему миру — от пустынь Афганистана до джунглей Африки.',
        OC: '64-bit Windows 7, 64-bit Windows 8 (8.1)',       
        Proc: 'Intel Core i5-4460 3.2GHz / AMD FX-8320',
        Vcard: 'NVIDIA GeForce GTX 650 / AMD Radeon HD 5850',
        OCR: 4.0,
        RCD: 28.0,
        RecOC: '64-bit Windows 7, 8.1, или 10',       
        RecProc: 'Intel Core i7-4790 3.6GHz / AMD FX-9370',
        RecVcard: 'NVIDIA GeForce GTX 760 / AMD Radeon R9 280',
        RecOCR: 8.0,
        RecRCD: 35.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/4/27863c41-74a9-4342-9b2e-2b4c493683dc.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/4/e3dc63a3-67b7-4348-b9f9-3ae0c41a234c.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/4/c8e23a0d-8279-4f78-94a9-a09d9670e003.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/4/77819b79-2a5f-460b-843b-76751bb08ae3.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/4/00277c6c-854d-4ebd-9c17-8694b13e721a.webp',
    },
    {
        id: 3,
        name: 'Dying Light',
        genre: 'Экшен, Шутеры, RPG',   
        date: '30 января 2015г',
        platform: 'PC, PlayStation 4',
        rating: 8.6,
        image: 'https://cdn.kanobu.ru/games/5da22a36-5b46-450c-aa2c-0cc333916e39.webp',
        description: 'Игрокам предстоит попасть в город, заполненный зомби, и исследовать его. Во время игры игрокам предстоит бегать по городской местности, создавать оружие для защиты от зараженных, а также сбор различных припасов для выживания.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Dying Light - это экшен-хоррор с видом от первого лица, с открытыми миром и эффектом сменяемости дня и ночи от компании Warner Bros. для PC, PS3, Xbox 360, PS4 и Xbox One. Игрокам предстоит попасть в огромный город, заполненный зомби, и исследовать его вдоль и поперек. Во время игры игрокам предстоит бегать по городской местности, создавать оружие и различные приспособлений для защиты от зараженных, а также сбор различных припасов для выживания.',
        OC: 'Windows® 7 64-bit / Windows® 8 64-bit ',       
        Proc: 'Intel® Core™ i5-2500 @3.3 GHz / AMD FX-8320 @3.5 GHz',
        Vcard: 'NVIDIA® GeForce® GTX 560 / AMD Radeon™ HD 6870 (1GB VRAM)',
        OCR: 4.0,
        RCD: 40.0,
        RecOC: 'Windows® 8 64-bit / Windows® 8.1 64-bit',       
        RecProc: 'Intel® Core™ i5-4670K @3.4 GHz / AMD FX-8350 @4.0 GHz',
        RecVcard: 'NVIDIA® GeForce® GTX 780 / AMD Radeon™ R9 290 (2GB VRAM)',
        RecOCR: 8.0,
        RecRCD: 45.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/53/d49a7d39-140e-4f25-9233-eb7afab2d846.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/53/5437845e-dcb1-493b-9ae3-c424bf12b4f0.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/53/d06264c1-835a-468b-bdb5-fe2f0d739c57.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/53/6711fdfc-37ad-4024-94b2-5bb87baacdba.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/53/344ab7a8-bfc8-4ad4-b2b7-b03b39c1673f.webp',
    },
    {
        id: 4,
        name: 'StarCraft 2: Legacy of the Void',
        genre: 'Стратегии, ММО',   
        date: '10 ноября 2015г',
        platform: 'PC, Mac',
        rating: 9.0,
        image: 'https://cdn.kanobu.ru/games/e9c94fb2-72f8-4dde-b839-282c57aeee04.webp',
        description: 'StarCraft 2: Legacy of the Void - это третья, и заключительная часть культовой стратегии в реальном времени, события которой разворачиваются параллельно с Heart of the Swarm и после его окончания.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'StarCraft 2: Legacy of the Void - это третья, и заключительная часть культовой стратегии в реальном времени, события которой разворачиваются параллельно с Heart of the Swarm и после его окончания. Главным героем этой части вновь станет Зератул, однако игрокам предстоит взять на себя роль не лидера Темных Тамплиеров Протоссов, а Артаниса, командира протоссов, который надеется отбить родную планету протоссов - Айур - у зергов, а затем помочь Зератулу с разгадкой древнего пророчества, от которого зависит судьба всей вселенной. ',
        OC: 'Windows® XP/Windows Vista®/Windows® 7',       
        Proc: 'Intel® Pentium® D или AMD Athlon™ 64 X2',
        Vcard: 'NVIDIA® GeForce® 7600 GT или ATI™ Radeon™ X800 XT',
        OCR: 1.5,
        RCD: 20.0,
        RecOC: 'Windows® 7/Windows® 8',       
        RecProc: 'Intel® Pentium® D или AMD Athlon™ 64 X2',
        RecVcard: 'NVIDIA® GeForce® 7600 GT или ATI™ Radeon™ X800 XT',
        RecOCR: 2.0,
        RecRCD: 30.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/21/5182f3b7-697b-4a21-910a-fbd1b4cb44fa.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/21/0ae7bb57-1f77-4e33-b6c8-1a9e451098d8.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/21/9623ecdb-fb00-4850-9300-1edff881de32.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/21/ba221210-f90d-47d3-82e0-5777637b983d.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/21/86aa4af5-03d7-4bcc-9fcb-a7e70f312ab9.webp',
    },
    {
        id: 5,
        name: 'Fallout 4',
        genre: 'Экшен, RPG',   
        date: '10 ноября 2015г',
        platform: 'PC, PlayStation 4',
        rating: 7.0,
        image: 'https://cdn.kanobu.ru/games/86eadbca-3700-448a-b226-faa764413a4f.webp',
        description: 'Fallout 4 - это продолжение знаменитой постапокалиптической серии, события которой развиваются спустя несколько лет после окончания Fallout 3. Протагонистом игры становится единственный выживший из Убежища 111.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Fallout 4 - это продолжение знаменитой постапокалиптической серии, события которой развиваются спустя несколько лет после окончания Fallout 3. Протагонистом игры становится единственный выживший из Убежища 111, которое находилось неподалеку от Бостона. Волей судьбы главному герою предстоит покинуть свой дом, чтобы пуститься в полное опасностей приключение, где на пути у него будут стоять мутанты, рейдеры, наемники и различные стихийные опасности.',
        OC: 'Windows 7/8/10',       
        Proc: 'Intel Core i5-2300 2.8 GHz/AMD Phenom II X4 945 3.0 GHz',
        Vcard: 'NVIDIA GTX 550 Ti 2GB/AMD Radeon HD 7870 2GB',
        OCR: 8.0,
        RCD: 30.0,
        RecOC: 'Windows 7/8/10',       
        RecProc: 'Intel Core i7 4790 3.6 GHz/AMD FX-9590 4.7 GHz or equivalent',
        RecVcard: 'NVIDIA GTX 780 3GB/AMD Radeon R9 290X 4GB or equivalent',
        RecOCR: 8.0,
        RecRCD: 40.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/76/a87ee537-d713-4c5f-b65a-ff4be3f3da7f.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/76/d0df6bc6-82ad-4045-88d0-55ca80a5c0e5.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/76/5db77ea7-ec05-4dc9-aa1b-bafc510402f9.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/76/fa5da0db-dcfa-458e-b484-439778f38f86.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/76/d09220e9-9218-49e7-aaf1-fd22660d0dbb.webp',
    },
    {
        id: 6,
        name: 'Undertale',
        genre: 'Аркады, RPG',   
        date: '15 сентября 2015г',
        platform: 'PC, PlayStation 4',
        rating: 9.2,
        image: 'https://cdn.kanobu.ru/games/5bd2ab2a-7bd0-4c43-ad37-407bbc70d2f8.webp',
        description: 'Undertale — это ролевая игра, в которой игрок может сражаться или мирно решать конфликты с монстрами, полностью меняя ход сюжета. В отличие от типичных RPG, Undertale предлагает уникальную боевую систему.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Undertale — инди-RPG от разработчика Тоби Фокса, вышедшая в 2015 году. В этой игре игрок управляет ребёнком, упавшим в Подземелье — магический мир, населённый монстрами. В отличие от типичных RPG, Undertale предлагает уникальную боевую систему, где каждый бой можно пройти без насилия — с помощью диалога, сострадания и наблюдательности. Игровой процесс включает элементы пошаговой стратегии, аркады и головоломок, а сюжет — насыщен юмором, философскими вопросами и эмоциональными моментами. Решения игрока — убивать или щадить — радикально влияют на развитие истории и концовку игры, делая каждый повторный проход уникальным.',
        OC: 'Windows® XP / Vista / 7 / 8 / 10',       
        Proc: 'Intel® Pentium® 4 @1.7 GHz',
        Vcard: 'NVIDIA® GeForce® 6200 (128MB VRAM, DirectX 9.0c)',
        OCR: 2.0,
        RCD: 0.2,
        RecOC: 'Windows® 7 64-bit / Windows® 10 64-bit',       
        RecProc: 'Intel® Core™ 2 Duo E8400 @3.0 GHz / AMD Athlon™ II X2 260',
        RecVcard: 'NVIDIA® GeForce® 210 / AMD Radeon™ HD 5450 (512MB VRAM)',
        RecOCR: 4.0,
        RecRCD: 0.5,
        Screen: 'https://cdn.kanobu.ru/screenshots/59/17b830f7-300c-42c2-9bd2-495ca64ec251.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/59/1f731787-2e2d-45be-9757-0b530b999510.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/59/68f105d9-3419-4d48-b723-00db672908f7.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/59/e8c1ec4c-8fa9-4cff-8bc5-38cad9c904a0.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/59/1728e139-a41e-437a-8842-8d701dbe12f1.webp',
    },
    {
        id: 7,
        name: 'The Forest',
        genre: 'Экшен, Симуляторы',   
        date: '30 мая 2015г',
        platform: 'PC, PlayStation 4',
        rating: 7.4,
        image: 'https://cdn.kanobu.ru/games/0d381232-16e0-42d9-b399-97aacd620f32.webp',
        description: 'The Forest - это мрачная sandbox-игра про выживание в ночном лесу, полном монстров. Игроки попадают на остров в результате авиакатастрофы, после чего узнают, что на острове они не одиноки - там же живет племя каннибалов.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'The Forest - это мрачная sandbox-игра про выживание в ночном лесу, полном монстров. Игроки попадают на остров в результате авиакатастрофы, после чего узнают, что на острове они не одиноки - там же живет племя туземцев-каннибалов, которые начинают преследовать протагониста.  Живут туземцы в пещерах и спят днем, поэтому днем игроки могут или собирать ресурсы, или устраивать набеги в пещеры, чтобы расправляться с каннибалами, оберегая себя от будущих нападений.',
        OC: 'Windows 7',       
        Proc: 'Intel Dual-Core 2.4 GHz',
        Vcard: 'NVIDIA GeForce 8800GT',
        OCR: 4.0,
        RCD: 5.0,
        RecOC: 'Windows 7',       
        RecProc: 'Quad Core Processor',
        RecVcard: 'NVIDIA GeForce GTX 560',
        RecOCR: 4.0,
        RecRCD: 10.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/9a0ff8b5-b4ce-4d94-9455-29f2021c2b76.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/54c74c6e-64c2-49a8-965f-2a2668db1a4b.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/8394c59a-2263-4499-bd5c-a34d8ea0cf1a.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/d62e01c4-3636-45b7-984e-06eb69887ded.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/f5bcffb5-0b3d-45e0-ab6f-b3f1a8bc22f0.webp',
    },
    {
        id: 8,
        name: 'Need for Speed (2015)',
        genre: 'Аркады, Гонки',   
        date: '3 ноября 2015г',
        platform: 'PC, PlayStation 4',
        rating: 8.0,
        image: 'https://cdn.kanobu.ru/games/31929f8a-dfc9-4413-87f9-7aa7c508f241.webp',
        description: 'Need for Speed (2015) - этот перезапуск серии Need For Speed с открытым миром, тюнингом автомобилей, а так же реалистичной графикой, созданной специально для устройств последнего поколения.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Need for Speed (2015) — это перезапуск легендарной серии гоночных аркад от студии Ghost Games и компании Electronic Arts. Игра предлагает атмосферу уличных гонок с упором на тюнинг, скорость и стиль, вдохновлённую духом таких частей, как Underground и Most Wanted. События разворачиваются в вымышленном городе Вентура-Бэй, где игрок становится восходящей звездой стритрейсинга. В игре представлено пять направлений карьеры: Скорость, Стиль, Построение, Команда и Закон, каждая из которых представляет свой уникальный стиль вождения и задач. Игроки могут кастомизировать внешний вид и характеристики автомобилей, участвовать в гонках, дрифт-соревнованиях и выполнять задания, взаимодействуя с реальными легендами автоспорта.',
        OC: 'Windows® 7 64-bit / Windows® 8 64-bit',       
        Proc: 'Intel® Core™ i3-4130 @3.4 GHz / AMD FX-6350 @3.9 GHz',
        Vcard: 'NVIDIA® GeForce® GTX 750 Ti / AMD Radeon™ HD 7850 (2 GB VRAM)',
        OCR: 6.0,
        RCD: 30.0,
        RecOC: 'Windows® 8.1 64-bit / Windows® 10 64-bit',       
        RecProc: 'Intel® Core™ i5-4690 @3.5 GHz / AMD FX-8350 @4.0 GHz',
        RecVcard: 'NVIDIA® GeForce® GTX 970 / AMD Radeon™ R9 290 (4 GB VRAM)',
        RecOCR: 8.0,
        RecRCD: 40.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/64/c2eb6e13-4a14-403f-9d3f-97f4d6148114.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/64/06c3b6d7-c8db-4a5f-9a24-0b9e3970b55b.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/64/8c019090-276d-4b96-a91f-279d9c90bba1.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/64/95d08029-290f-4ffd-b8dd-dd3c6e179e84.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/64/e01b4d96-fcd0-42f4-bf5c-24df42d70f48.webp',
    },
    {
        id: 9,
        name: 'Mad Max',
        genre: 'Экшен',   
        date: '4 сентября 2015г',
        platform: 'PC, PlayStation 4',
        rating: 7.3,
        image: 'https://cdn.kanobu.ru/games/a10e630b-f8d3-4034-9fb1-7740178cbb88.webp',
        description: 'Mad Max - это компьютерная игра в жанре action от третьего лица. Действие игры разворачивается в постапокалиптическом будущем, а главным героем выступает Макс Рокатански - бывший офицер, герой фильмов "Безумный Макс". ',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Mad Max - это компьютерная игра в жанре action от третьего лица. Действие игры разворачивается в постапокалиптическом будущем, а главным героем выступает Макс Рокатански - бывший офицер полиции, герой фильмов "Безумный Макс". События игры разворачиваются на территории постапокалиптической Австралии, где мало воды, но много воинственных кланов и группировок.',
        OC: '64 bit: Vista, Win 7, Win 8, Win 10',       
        Proc: 'Intel Core i5-650, 3.2 GHz or AMD Phenom II X4 965, 3.4 Ghz',
        Vcard: 'NVIDIA GeForce GTX 660ti (2 GB Memory or higher)',
        OCR: 6.0,
        RCD: 32.0,
        RecOC: '64 bit: Win 7 SP1, Win 8.1, Win 10',       
        RecProc: 'Intel Core i7-3770, 3.4 GHz or AMD FX-8350, 4.0 GHz',
        RecVcard: 'NVIDIA GeForce GTX 760 (3 GB Memory or higher)',
        RecOCR: 8.0,
        RecRCD: 40.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/5/640972b0-fa74-40af-84b1-9cf6175e8105.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/5/9437df87-b842-422f-bf6e-0c92469fdde1.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/5/9346d6c5-e24a-4dfa-87bd-99d8cb2b5182.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/5/2abb4682-d8ae-4ca4-98e2-2fa5b39955f6.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/5/ed26bf69-3b42-48d7-977b-37a40b55df9b.webp',
    },
    {
        id: 10,
        name: 'Mortal Kombat X',
        genre: 'Аркады, Файтинги',   
        date: '14 апреля 2015г',
        platform: 'PC, PlayStation 4',
        rating: 8.5,
        image: 'https://cdn.kanobu.ru/games/3e90390e-482a-4075-9c13-ccfc6d851d7b.webp',
        description: 'Mortal Kombat X - это десятая часть знаменитого файтинга Mortal Kombat,  использующая технологии нового поколения, а так же сочетающая в себе динамичный геймплей и кинематографичную картинку.',
        closeButtonImg: 'https://cdn-icons-png.flaticon.com/128/151/151882.png',
        allDescription: 'Mortal Kombat X — это зрелищный и жестокий файтинг от студии NetherRealm Studios, ставший продолжением легендарной серии. Игра объединяет культовых персонажей, кровавые добивания и современную графику, выводя франшизу на новый уровень. Сюжет охватывает несколько десятилетий и рассказывает о противостоянии между силами Земного царства и потусторонними угрозами, включая Шиннока и его армию. Впервые в серии представлены новые герои — дети и ученики старых бойцов, таких как Кэсси Кейдж, Такеда и Джеки Бриггс. Каждый персонаж имеет по три уникальных боевых стиля, что даёт глубину геймплею и разнообразие в поединках. В игре также реализована улучшенная система X-Ray-ударов и брутальные фаталити, ставшие фирменной чертой Mortal Kombat.',
        OC: 'Windows® 7 64-bit',       
        Proc: ' Intel® Core™ i5-750 @2.67 GHz / AMD Phenom™ II X4 965 @3.4 GHz',
        Vcard: 'NVIDIA® GeForce® GTX 460 / AMD Radeon™ HD 5850 (1 GB VRAM)',
        OCR: 3.0,
        RCD: 36.0,
        RecOC: 'Windows® 7, 8, 10 (64-bit)',       
        RecProc: 'Intel® Core™ i7-3770 @3.4 GHz / AMD FX-8350 @4.0 GHz',
        RecVcard: 'NVIDIA® GeForce® GTX 660 / AMD Radeon™ HD 7950 (2 GB VRAM)',
        RecOCR: 8.0,
        RecRCD: 50.0,
        Screen: 'https://cdn.kanobu.ru/screenshots/0/6b6c388b-39b2-494b-a803-e0342c736d94.webp',
        Screen_2: 'https://cdn.kanobu.ru/screenshots/0/32bc52ac-f88f-4f87-8e37-896e4b56c7b8.webp',
        Screen_3: 'https://cdn.kanobu.ru/screenshots/0/b358e93e-db1b-4deb-a531-1db8c895fbce.webp',
        Screen_4: 'https://cdn.kanobu.ru/screenshots/0/33d40888-2e56-4344-b2aa-c27f8d49437f.webp',
        Screen_5: 'https://cdn.kanobu.ru/screenshots/0/2c2e6ada-d946-41d4-b690-514354ca0dfb.webp',
    },
]

export default Product